chore(code coverage service): Add coveralls badge
andela/ah-technocrats pull request #3
Opened 2018-11-27 08:14 UTC by salma-nyagaka

#### What does this PR do?
Add coveralls to the project and the badge to README.md
#### Description of Task to be completed?
Integrate Coveralls code coverage service
#### How should this be manually tested?
To test the application follow the steps below.
 - Clone the repo using `git clone https://github.com/andela/ah-technocrats.git`
- `git checkout ch-add-coveralls-161966602`
 - ` cd ah-technocrats`
 - run `virtualenv env -p python3` to create a virtual environment for the application
 - Activate the environment `source env/activate/activate`
 - Install required modules  using `pip install -r requirements.txt`
 - run `python manage.py test` to test
#### Any background context you want to provide?
- This is to ensure we are properly informed just how well our code base is tested which in turn provides quality assurance for the product
#### What are the relevant pivotal tracker stories?
[#161966602](https://www.pivotaltracker.com/n/projects/2225606)

2018-11-27 08:16 UTC, verenceLola commented
Next time please tag reviewers.

2018-11-27 11:08 UTC, SnyderMbishai commented
Good work on this!

2018-11-27 11:09 UTC, SnyderMbishai submitted a review, later dismissed

2018-11-27 11:17 UTC, verenceLola submitted a review, later dismissed
Good work @salma-nyagaka for delivering your work in time.

2018-11-27 14:46 UTC, Mnickii submitted a review, later dismissed
LGTM. Rebase your PR

2018-11-28 13:10 UTC, SilasKenneth submitted a review, later dismissed

2018-11-28 13:38 UTC, SilasKenneth submitted a review, later dismissed

2018-11-28 16:33 UTC, SilasKenneth submitted a review, later dismissed

2018-11-28 17:39 UTC, SnyderMbishai commented
Good work, please check the PR, there should be a question mark after 'How should this be manually tested'.

2018-11-28 18:23 UTC, kipropbrian commented
This commit has issues too, as do the others. It appears you did not rebase correctly

2018-11-29 04:06 UTC, Mnickii requested changes
Your PR has too many changes unrelated to adding a coveralls badge and updating the readme. Fix this

2018-11-29 04:06 UTC, Mnickii commented on authors/apps/authentication/backends.py
> +    """
These changes are out of scope of your PT story. Make sure this PR only addresses the story assigned

2018-11-29 07:21 UTC, actlikewill reviewed
Hope you were able to solve the conflicts ...

2018-11-29 10:08 UTC, Mnickii approved these changes
LGTM

2018-11-29 10:08 UTC, merged